# Generated by Django 5.1.1 on 2024-10-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionMetadata",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("start_ingestion_time", models.DateTimeField()),
                ("end_ingestion_time", models.DateTimeField()),
                (
                    "delta_category",
                    models.TextField(
                        choices=[("SECOND", "Second"), ("MINUTE", "Minute"), ("HOUR", "Hour"), ("DAY", "Day")]
                    ),
                ),
                ("delta_multiplier", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tickers",
            fields=[
                ("symbol", models.CharField(auto_created=True, max_length=4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("exchange", models.CharField(max_length=50, null=True)),
                ("industry", models.CharField(max_length=50, null=True)),
                ("sector", models.CharField(max_length=50, null=True)),
                ("country", models.CharField(max_length=50, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["symbol"], name="symbol_idx"),
                    models.Index(fields=["name"], name="name_idx"),
                    models.Index(fields=["exchange"], name="exchange_idx"),
                    models.Index(fields=["industry"], name="industry_idx"),
                    models.Index(fields=["sector"], name="sector_idx"),
                    models.Index(fields=["country"], name="country_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockIngestion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("ingestion_started_at", models.DateTimeField(null=True)),
                (
                    "ingestion_status",
                    models.TextField(
                        choices=[
                            ("ON_QUEUE", "On Queue"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DEPLOYING", "Deploying"),
                        ]
                    ),
                ),
                ("ingestion_finished_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stocks_metadata.ingestionmetadata"
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stocks_metadata.tickers"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockIdx",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "ticker",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stocks_metadata.tickers"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="created_at_idx"),
                    models.Index(fields=["updated_at"], name="updated_at_idx"),
                    models.Index(fields=["deleted"], name="deleted_idx"),
                ],
            },
        ),
    ]
