# Generated by Django 5.1.1 on 2024-10-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks_metadata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                ("key", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("value", models.TextField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["key"], name="key_idx"),
                    models.Index(fields=["value"], name="value_idx"),
                ],
            },
        ),
    ]
