# Generated by Django 5.1.1 on 2024-10-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks_metadata", "0002_appsettings"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tickers",
            name="industry_idx",
        ),
        migrations.RemoveIndex(
            model_name="tickers",
            name="sector_idx",
        ),
        migrations.RemoveIndex(
            model_name="tickers",
            name="country_idx",
        ),
        migrations.RemoveField(
            model_name="tickers",
            name="country",
        ),
        migrations.RemoveField(
            model_name="tickers",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="tickers",
            name="sector",
        ),
        migrations.AddField(
            model_name="tickers",
            name="relations",
            field=models.ManyToManyField(to="stocks_metadata.tickers"),
        ),
        migrations.AddField(
            model_name="tickers",
            name="type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
