# Generated by Django 5.1.1 on 2024-10-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks_metadata", "0003_remove_tickers_industry_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickers",
            name="symbol",
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
