# Generated by Django 5.1.1 on 2024-10-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks_metadata", "0005_create_inital_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockingestion",
            name="ingestion_deployed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
